<?php
declare(strict_types=1);

require_once __DIR__ . '/backend-common.php';
require_once __DIR__ . '/backend-layout.php';
backend_require_roles(['deptmanager', 'assetmanager']);

backend_render_header('零件庫存與後台主管審核', '盤點耗材庫存，並簽核缺件/補貨申請。', true);
?>
<div class="tab-bar"><button class="admin-button" data-tab="stock">耗材零件庫存盤點</button><button class="admin-button" data-tab="requests">後台主管審核收件匣</button></div><section class="admin-panel" id="stock-tab"><h2>庫存盤點</h2><div id="stock-list"></div></section><section class="admin-panel" id="requests-tab" style="display:none;"><h2>待審單據</h2><div id="request-list"></div></section>
<script>
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
let payload={parts:[],requests:[]};
async function loadStock(){const r=await fetch('api/stock_review.php',{credentials:'same-origin'}); const p=await r.json(); if(!p.ok)throw new Error(p.error||'讀取失敗'); payload=p.data; renderStock(); renderRequests();}
function renderStock(){document.getElementById('stock-list').innerHTML=`<table><thead><tr><th>零件</th><th>庫存</th><th>安全庫存</th><th>建議補貨</th><th>狀態</th><th>儲存</th></tr></thead><tbody>${payload.parts.map(p=>`<tr><td>${esc(p.part_id)}<div class="small muted">${esc(p.part_name||'')}</div></td><td><input type="number" min="0" value="${esc(p.stock??0)}" data-stock="${esc(p.part_id)}"></td><td><input type="number" min="0" value="${esc(p.safe_stock??0)}" data-safe="${esc(p.part_id)}"></td><td><input type="number" min="0" value="${esc(p.reorder_qty??0)}" data-reorder="${esc(p.part_id)}"></td><td><span class="status-pill ${p.stock_state==='低庫存'?'danger':(p.stock_state==='即將不足'?'warning':'good')}">${esc(p.stock_state)}</span></td><td><button class="admin-button" data-save="${esc(p.part_id)}">儲存</button></td></tr>`).join('')}</tbody></table>`; document.querySelectorAll('[data-save]').forEach(b=>b.onclick=()=>savePart(b.dataset.save));}
async function savePart(partId){const body={action:'update_stock',part_id:partId,stock:document.querySelector(`[data-stock="${partId}"]`).value,safe_stock:document.querySelector(`[data-safe="${partId}"]`).value,reorder_qty:document.querySelector(`[data-reorder="${partId}"]`).value}; const r=await fetch('api/stock_review.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify(body)}); const p=await r.json(); alert(p.ok?'庫存已更新':(p.error||JSON.stringify(p.errors))); if(p.ok)loadStock();}
function renderRequests(){document.getElementById('request-list').innerHTML=payload.requests.length?`<table><thead><tr><th>單據</th><th>維修單</th><th>申請者</th><th>明細</th><th>狀態</th><th>決策</th></tr></thead><tbody>${payload.requests.map(r=>`<tr><td>${esc(r.request_id)}</td><td>${esc(r.maint_id)}<div class="small muted">${esc(r.maintenance_status||'')}</div></td><td>${esc(r.technician_name||r.technician_id)}</td><td>${esc(r.parts_summary||'-')}</td><td>${esc(r.status)}</td><td>${r.status==='待審'?`<button class="admin-button" data-approve="${esc(r.request_id)}">核准</button> <button class="admin-button" data-reject="${esc(r.request_id)}">駁回</button>`:'-'}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">目前沒有申請單。</div>'; document.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>decide(b.dataset.approve,'批准')); document.querySelectorAll('[data-reject]').forEach(b=>b.onclick=()=>decide(b.dataset.reject,'駁回'));}
async function decide(requestId,decision){let reject_reason=''; if(decision==='駁回'){reject_reason=prompt('請填寫駁回原因')||''; if(!reject_reason)return;} const r=await fetch('api/stock_review.php',{method:'POST',headers:{'Content-Type':'application/json'},credentials:'same-origin',body:JSON.stringify({action:'decide_request',request_id:requestId,decision,reject_reason})}); const p=await r.json(); alert(p.ok?'簽核完成':(p.error||JSON.stringify(p.errors))); if(p.ok)loadStock();}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.getElementById('stock-tab').style.display=b.dataset.tab==='stock'?'block':'none';document.getElementById('requests-tab').style.display=b.dataset.tab==='requests'?'block':'none';});
loadStock().catch(e=>document.getElementById('stock-list').innerHTML=`<div class="error-box">${esc(e.message)}</div>`);
</script>
<?php backend_render_footer(); ?>